#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy

source ${SOURCE_DIR}/config

(
	cd ${CURRENT_DIR}

	echo "*************** About to do pip install (pwd: $(pwd)) ***************"

	if [ -f ${CURRENT_DIR}/requirements.txt ]; then
		sudo pip install -r ${CURRENT_DIR}/requirements.txt
	elif [ -f ${CURRENT_DIR}/setup.py ]; then
		sudo pip install ${CURRENT_DIR}/
	fi
)

echo "*********** Running any hooks in ${SOURCE_DIR}/hooks.py ***************"
/home/application/.venv/bin/python ${SOURCE_DIR}/hooks.py
